const router = require('express').Router()
const checkAdmin = require('../middlewares/checkAdmin')
const checkAuth = require('../middlewares/checkAuth');
const SellerAuth = require('../middlewares/SellerAuth')
const {findTheProduct, addToCart,fetchMyCart,incCart,decCart, deleteFromCart, findMyOrders, placeOrder, showAddressPage, showChangePass, showSeller, showAdmin, showForget, handleForget, showForgetpass, changepassword, forgotchangepassword} = require('../controllers/UserCon')
const checkRequest = require('../middlewares/forgotRequest')
router.get('/Admin',checkAdmin,showAdmin)
router.get('/home',checkAuth,findTheProduct)
router.post('/addtocart',checkAuth,addToCart)
router.get('/mycart',checkAuth,fetchMyCart)
router.post('/inccart',checkAuth,incCart)
router.post('/deccart',checkAuth,decCart)
router.post('/dcart',checkAuth,deleteFromCart)
router.get('/myorders',checkAuth,findMyOrders)
router.post('/order',checkAuth,placeOrder)
router.get('/changePassword',checkAuth,showChangePass)
router.get('/Seller',SellerAuth,showSeller)
router.get('/forgotpass',showForget)
router.post('/forgetpass',handleForget)
router.get('/forgotchangepassword',showForgetpass)
router.get('/order',checkAuth,showAddressPage)
router.post('/changepassword',checkAuth,changepassword)
router.post('/forgotchangepassword',checkRequest,forgotchangepassword)
module.exports = router;